[package]
name = "norad"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2018"

[dependencies]
plist = "0.4"
serde = "1.0"
serde_derive = "1.0"
quick-xml = "0.12.0"

[dev-dependencies]
failure = "*"
